name: VPS_Linux_via_Tailscale

on:
  # Opsi untuk menjalankan workflow secara manual
  workflow_dispatch:

jobs:
  secure-ssh-vps:
    # Menggunakan runner Linux terbaru
    runs-on: ubuntu-latest
    # Batas waktu maksimum 60 jam (Anda harus membatalkan secara manual setelah selesai)
    timeout-minutes: 3600

    steps:
      - name: Mengatur SSH dan Firewall 🔒
        run: |
          # Pastikan OpenSSH server terinstal
          sudo apt update
          sudo apt install -y openssh-server
          
          # Mengizinkan login menggunakan password (diperlukan untuk pengguna yang dibuat)
          sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
          
          # Restart layanan SSH
          sudo service ssh restart
          
          # Aturan Firewall: Izinkan Tailscale dan SSH
          sudo ufw allow 41641/udp
          sudo ufw allow 22/tcp
          sudo ufw --force enable

      - name: Membuat Pengguna SSH yang Aman 👤
        run: |
          # Membuat password acak yang aman
          PASSWORD=$(openssl rand -base64 12 | tr -d '=+/' | cut -c1-16)
          USERNAME="gh_user"
          
          # Membuat pengguna baru
          sudo useradd -m -s /bin/bash "$USERNAME"
          echo "$USERNAME:$PASSWORD" | sudo chpasswd
          
          # Tambahkan pengguna ke grup sudo (Administrator)
          sudo usermod -aG sudo "$USERNAME"
          
          echo "SSH_CREDS=User: $USERNAME | Password: $PASSWORD" >> $GITHUB_ENV
          
          if ! id -u "$USERNAME" > /dev/null 2>&1; then
              echo "User creation failed"
              exit 1
          fi

      - name: Menginstal Tailscale 🦎
        run: |
          curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.tgz | tar zx
          sudo cp -r jammy/tailscale /usr/bin/
          sudo cp -r jammy/tailscaled /usr/sbin/
          sudo rm -rf jammy
          
          # Mulai daemon Tailscale
          sudo tailscaled &
          sleep 5

      - name: Menghubungkan ke Tailnet (Membutuhkan Secret) 🔗
        # Gunakan secret TAILSCALE_AUTH_KEY yang sudah Anda buat
        run: |
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-$GITHUB_RUN_ID
          
          # Menunggu hingga IP Tailscale ditetapkan
          TS_IP=""
          RETRY_COUNT=0
          while [ -z "$TS_IP" ] && [ $RETRY_COUNT -lt 10 ]; do
              TS_IP=$(sudo tailscale ip -4)
              sleep 5
              RETRY_COUNT=$((RETRY_COUNT + 1))
          done
          
          if [ -z "$TS_IP" ]; then
              echo "Tailscale IP not assigned. Exiting."
              exit 1
          fi
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV
      
      - name: Memelihara Koneksi & Menampilkan Kredensial ✨
        run: |
          echo -e "\n======================="
          echo "=== AKSES VPS AKTIF ==="
          echo "=======================\n"
          
          # IP Tailscale adalah alamat yang Anda gunakan (tanpa domain)
          echo "Alamat IP Tailscale: $TAILSCALE_IP"
          echo "Port SSH: 22"
          echo "Username: gh_user"
          echo "Password: $(echo $SSH_CREDS | awk '{print $NF}')"
          echo -e "\n-----------------------"
          echo "PERINTAH UNTUK ANDA:"
          echo "ssh gh_user@$TAILSCALE_IP"
          echo "-----------------------\n"
          
          # Skrip ini akan terus berjalan, menjaga VPS tetap aktif
          while true; do
              echo "[$(date)] Sesi VPS Aktif - Batalkan workflow untuk mematikan"
              sleep 300
          done
